/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

public class App {
    //кол-во потоков
    private static final int threadCount = 2;
    private static final int counterMaxValue = 10;
    private static final int counterMinValue = 1;

    public static void main(String[] args) {
        var counter = new ThreadStarter();
        counter.start();
    }

}
