/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

import java.io.Console;
import java.util.HashMap;
import java.util.Map;

public class App {
    public static void main(String[] args) {
    }
}
