/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package otus;

public class App {
    public static void main(String[] args) {
        HelloOtus.GuavaExampleIntMath_checkedAdd(10, 20);
    }
}
