/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homework;

public class App {
    public static void main(String[] args) {
        TestRunner.run("homework.tests.TestClass", 1, 1);
    }
}
